[package]
name = "notion-api"
version = "0.0.0"
authors = ["bachrc <bachrc@dessert.coffee>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
